const products = [
    // ── CERÁMICA (8) ──
    { id: 1, cat: 'ceramica', title: 'Jarrón Azul de la Alhambra', artisan: 'María Ruiz', initials: 'MR', live: true, region: 'Granada, Andalucía', price: 89, badge: '1 de 1', quote: '«Cada curva nace del silencio de mi taller al amanecer.»', img: 'assets/images/product-vase.png', polaroids: ['🏺 Torno', '🎨 Esmalte', '🔥 Horno'], story: 'María usa técnicas nazaríes del siglo XIV. El azul cobalto proviene de minerales locales de Sierra Nevada.', details: ['Cerámica', 'Hecho a mano', 'Azul cobalto', 'Alt. 35cm'] },
    { id: 2, cat: 'ceramica', title: 'Cuenco Terracota del Mediterráneo', artisan: 'José Pérez', initials: 'JP', live: false, region: 'Valencia', price: 54, badge: 'Artesanal', quote: '«El barro me cuenta secretos que solo mis manos pueden escuchar.»', img: 'assets/images/product-bowl.png', polaroids: ['👐 Moldeado', '☀️ Secado', '🖌️ Pintura'], story: 'José trabaja la terracota valenciana desde hace 30 años. Cada cuenco pasa 3 días secándose al sol mediterráneo.', details: ['Terracota', 'Apto alimentos', 'Ø 22cm'] },
    { id: 3, cat: 'ceramica', title: 'Plato Talavera Flores del Jardín', artisan: 'Carmen López', initials: 'CL', live: true, region: 'Toledo, Castilla-La Mancha', price: 127, badge: 'Ed. Limitada', quote: '«Pinto flores porque mi abuela me enseñó que la belleza es resistencia.»', img: 'assets/images/product-plate.png', polaroids: ['✏️ Boceto', '🎨 Color', '✨ Acabado'], story: 'La técnica Talavera de Carmen procede de 4 generaciones. Usa pigmentos naturales extraídos de plantas locales.', details: ['Talavera', 'Pigmentos naturales', 'Decorativo', 'Ø 30cm'] },
    { id: 4, cat: 'ceramica', title: 'Botijo Clásico de Úbeda', artisan: 'Antonio García', initials: 'AG', live: true, region: 'Úbeda, Andalucía', price: 45, badge: 'Tradicional', quote: '«Un botijo no enfría agua, enfría el alma en verano.»', img: 'assets/images/product-jug.png', polaroids: ['🏺 Arcilla', '👐 Forma', '💧 Prueba'], story: 'El botijo de Antonio usa arcilla roja de Úbeda. El agua se enfría 8°C gracias a la porosidad natural.', details: ['Arcilla roja', 'Funcional', 'Cap. 3L'] },
    { id: 5, cat: 'ceramica', title: 'Azulejos Nazaríes Set Geométrico', artisan: 'Taller Alhambra', initials: 'TA', live: false, region: 'Granada, Andalucía', price: 96, badge: 'Set de 4', quote: '«Cada línea geométrica es una oración silenciosa en cerámica.»', img: 'assets/images/product-tiles.png', polaroids: ['📐 Diseño', '🎨 Esmaltado', '🧱 Montaje'], story: 'Reproducción fiel de los azulejos del Patio de los Leones. Cada pieza se esmalta individualmente.', details: ['Azulejo', 'Mural', '15x15cm c/u', 'Certificado'] },
    { id: 6, cat: 'ceramica', title: 'Jarra Mudéjar de Teruel', artisan: 'Pablo Martínez', initials: 'PM', live: false, region: 'Teruel, Aragón', price: 78, badge: 'Artesanal', quote: '«El verde de cobre y el morado de manganeso son mis dos amores.»', img: 'assets/images/Jarra-Mudéjar-de-Teruel.jpg', polaroids: ['🏺 Torno', '🧪 Óxidos', '🔥 Cocción'], story: 'Pablo recupera la cerámica mudéjar turolense. Los óxidos de cobre dan el verde característico.', details: ['Mudéjar', 'Óxidos naturales', 'Cap. 1.5L'] },
    { id: 7, cat: 'ceramica', title: 'Taza Sargadelos Atlántica', artisan: 'Elena Vidal', initials: 'EV', live: true, region: 'Lugo, Galicia', price: 32, badge: 'Colección', quote: '«El azul de Sargadelos es el azul del Atlántico embotellado.»', img: 'assets/images/Taza-Sargadelos-Atlántica.jpg', polaroids: ['💧 Barbotina', '🌊 Diseño', '☕ Uso'], story: 'Sargadelos lleva más de 200 años creando porcelana en Galicia. Elena diseña piezas que unen tradición y vanguardia.', details: ['Porcelana', 'Apto microondas', '250ml'] },
    { id: 8, cat: 'ceramica', title: 'Maceta Granadina Pintada', artisan: 'Lucía Campos', initials: 'LC', live: false, region: 'Granada, Andalucía', price: 42, badge: 'Artesanal', quote: '«Mis macetas son pequeños jardines antes de tener plantas.»', img: 'assets/images/Maceta-Granadina-Pintada.jpg', polaroids: ['🌿 Inspiración', '🖌️ Pintado', '☀️ Secado'], story: 'Lucía pinta cada maceta con motivos del Albaicín. Usa esmaltes resistentes a la intemperie.', details: ['Cerámica esmaltada', 'Exterior', 'Ø 18cm'] },

    // ── TEXTIL (5) ──
    { id: 9, cat: 'textil', title: 'Chal de Lana Merina Índigo', artisan: 'Lucía Fernández', initials: 'LF', live: false, region: 'Ezcaray, La Rioja', price: 78, badge: 'Tintes Nat.', quote: '«Cada hilo que tejo conecta a la persona con la tierra.»', img: 'assets/images/product-textile.png', polaroids: ['🐑 Lana', '🧶 Hilado', '🌿 Tinte'], story: 'La lana merina de Ezcaray se tiñe con índigo natural. Un chal tarda 3 semanas en completarse.', details: ['Lana merina', 'Tinte natural', '180x60cm'] },
    { id: 10, cat: 'textil', title: 'Manta Alpujarreña de Telar', artisan: 'Rosa Jiménez', initials: 'RJ', live: true, region: 'Alpujarras, Granada', price: 195, badge: 'Pieza Única', quote: '«Mi telar es un instrumento musical que teje melodías de lana.»', img: 'assets/images/product-wovenblanket.png', polaroids: ['🧵 Urdimbre', '👐 Telar', '🌞 Tendido'], story: 'Rosa usa un telar del siglo XVIII. Cada manta lleva los colores de la Alpujarra: blanco, azul y terracota.', details: ['Algodón y lana', 'Telar manual', '200x150cm'] },
    { id: 11, cat: 'textil', title: 'Tapiz de Esparto Mediterráneo', artisan: 'Isabel Torres', initials: 'IT', live: false, region: 'Murcia', price: 145, badge: 'Artesanal', quote: '«El esparto es humilde, pero en mis manos se convierte en arte.»', img: 'assets/images/Tapiz-de-Esparto-Mediterráneo.jpg', polaroids: ['🌾 Esparto', '✂️ Cortado', '🪢 Trenzado'], story: 'Isabel trenza esparto mediterráneo siguiendo técnicas romanas. Cada tapiz es un mapa de texturas.', details: ['Esparto natural', 'Pared', '120x80cm'] },
    { id: 12, cat: 'textil', title: 'Pañuelo de Seda Valenciano', artisan: 'Ana Beltrán', initials: 'AB', live: true, region: 'Valencia', price: 65, badge: 'Pintado a mano', quote: '«La seda es agua que puedes llevar puesta.»', img: 'assets/images/Pañuelo-de-Seda-Valencian.jpg', polaroids: ['🎨 Boceto', '🖌️ Pintura', '💨 Fijado'], story: 'Ana pinta a mano sobre seda valenciana. Los diseños se inspiran en la huerta y las flores de naranjo.', details: ['Seda natural', 'Pintado a mano', '90x90cm'] },
    { id: 13, cat: 'textil', title: 'Alfombra Jarapa Reciclada', artisan: 'Miguel Santos', initials: 'MS', live: false, region: 'Alpujarras, Granada', price: 88, badge: 'Eco', quote: '«Cada alfombra es una segunda vida para la ropa que ya no se usa.»', img: 'assets/images/Alfombra-Jarapa-Reciclada.jpg', polaroids: ['♻️ Reciclaje', '🧶 Tejido', '🏠 Casa'], story: 'Miguel teje jarapas con tiras de tela reciclada. Una tradición alpujarreña que combate el desperdicio textil.', details: ['Textil reciclado', 'Lavable', '150x100cm'] },

    // ── MADERA (5) ──
    { id: 14, cat: 'madera', title: 'Cucharas de Olivo Talladas', artisan: 'Fernando Ruiz', initials: 'FR', live: true, region: 'Jaén, Andalucía', price: 38, badge: 'Set de 3', quote: '«Tallo la madera de olivos centenarios que ya no dan fruto.»', img: 'assets/images/product-woodspoons.png', polaroids: ['🌳 Olivo', '🪓 Tallado', '🧴 Aceite'], story: 'Fernando rescata olivos centenarios. Cada cuchara conserva las vetas únicas del árbol original.', details: ['Olivo centenario', 'Acabado en aceite', 'Set 3 uds.'] },
    { id: 15, cat: 'madera', title: 'Caja Taracea Granadina', artisan: 'Marcos Alonso', initials: 'MA', live: false, region: 'Granada, Andalucía', price: 165, badge: 'Marquetería', quote: '«Cada diminuta pieza de madera es un pixel de una obra mayor.»', img: 'assets/images/product-woodbox.png', polaroids: ['🪚 Corte', '🧩 Montaje', '✨ Pulido'], story: 'La taracea granadina incrusta maderas de distintos colores formando geometrías morunas. Marcos domina 12 técnicas.', details: ['Maderas nobles', 'Taracea', '20x15x8cm'] },
    { id: 16, cat: 'madera', title: 'Tabla de Cortar Artesanal de Nogal', artisan: 'Carlos Méndez', initials: 'CM', live: true, region: 'Asturias', price: 72, badge: 'Funcional', quote: '«La cocina es mi galería y las tablas de cortar son mis cuadros.»', img: 'assets/images/Tabla-de-Cortar-Artesanal.jpg', polaroids: ['🌲 Selección', '🪓 Forma', '🧴 Acabado'], story: 'Carlos selecciona nogal asturiano caído naturalmente. Cada tabla se cura con aceite de nuez durante 2 semanas.', details: ['Nogal', 'Aceite de nuez', '45x25cm'] },
    { id: 17, cat: 'madera', title: 'Bastón de Peregrino del Camino', artisan: 'Diego Navarro', initials: 'DN', live: false, region: 'Sarria, Galicia', price: 55, badge: 'Camino', quote: '«Cada bastón ha caminado conmigo antes de acompañar a su dueño.»', img: 'assets/images/Bastón de Peregrino del Camino.jpg', polaroids: ['🌿 Castaño', '🔪 Tallado', '🐚 Concha'], story: 'Diego talla bastones de castaño gallego para peregrinos del Camino de Santiago. Incluye concha incrustada.', details: ['Castaño', '130cm', 'Concha real'] },
    { id: 18, cat: 'madera', title: 'Molinillo de Pimienta Torneado', artisan: 'Adrián Soto', initials: 'AS', live: true, region: 'Valencia', price: 48, badge: 'Funcional', quote: '«Un buen molinillo transforma una comida en un ritual.»', img: 'assets/images/Molinillo de Pimienta Torneado.jpg', polaroids: ['🌳 Cerezo', '🔧 Torno', '⚙️ Mecanismo'], story: 'Adrián tornea cerezo valenciano. El mecanismo cerámico muele sin oxidarse y dura décadas.', details: ['Cerezo', 'Mecanismo cerámico', '20cm alt.'] },

    // ── CUERO (4) ──
    { id: 19, cat: 'cuero', title: 'Bolso Bandolera de Ubrique', artisan: 'Patricia Molina', initials: 'PM', live: true, region: 'Ubrique, Cádiz', price: 189, badge: 'Premium', quote: '«El cuero de Ubrique guarda el secreto de la elegancia eterna.»', img: 'assets/images/Bolso Bandolera de Ubrique.jpg', polaroids: ['🐄 Curtido', '✂️ Corte', '🪡 Cosido'], story: 'Patricia trabaja con piel vacuna curtida al vegetal. Ubrique provee a las mejores casas de moda del mundo.', details: ['Piel vacuna', 'Curtido vegetal', '28x20cm'] },
    { id: 20, cat: 'cuero', title: 'Cinturón Trenzado a Mano', artisan: 'Raúl Castro', initials: 'RC', live: false, region: 'Córdoba', price: 75, badge: 'Artesanal', quote: '«Un buen cinturón es la columna vertebral de cualquier atuendo.»', img: 'assets/images/Cinturón-Trenzado-a-Mano.jpg', polaroids: ['🐄 Selección', '🪢 Trenzado', '🪣 Teñido'], story: 'Raúl trenza cuero cordobés con técnica ecuestre. Un cinturón requiere 8 hours de trabajo manual.', details: ['Piel de ternera', 'Trenzado manual', 'Tallas S-XL'] },
    { id: 21, cat: 'cuero', title: 'Cartera Repujada Cordobesa', artisan: 'Laura Herrero', initials: 'LH', live: true, region: 'Córdoba', price: 95, badge: 'Repujado', quote: '«Cada golpe del martillo sobre el cuero es como escribir braille para los ojos.»', img: 'assets/images/Cartera Repujada Cordobesa.jpg', polaroids: ['📐 Diseño', '🔨 Repujado', '🎨 Tintura'], story: 'Laura domina el repujado cordobés, arte declarado Patrimonio Inmaterial. Cada cartera tarda 2 semanas.', details: ['Piel de cabra', 'Repujado', '12x9cm'] },
    { id: 22, cat: 'cuero', title: 'Funda de Móvil en Piel', artisan: 'Sergio Reyes', initials: 'SR', live: false, region: 'Ubrique, Cádiz', price: 45, badge: 'Funcional', quote: '«Proteger lo que más tocas merece la mejor piel.»', img: 'assets/images/Funda-de-Móvil-en-Piel.jpg', polaroids: ['✂️ Corte', '🪡 Cosido', '📱 Ajuste'], story: 'Sergio fabrica fundas a medida para cada modelo de teléfono. Piel curtida artesanalmente en Ubrique.', details: ['Piel curtida', 'A medida', 'Varios modelos'] },

    // ── VIDRIO (4) ──
    { id: 23, cat: 'vidrio', title: 'Copa de Cristal Soplado', artisan: 'Inmaculada Ríos', initials: 'IR', live: true, region: 'La Granja, Segovia', price: 68, badge: 'Soplado', quote: '«El vidrio fundido es fuego líquido que moldeo con mi aliento.»', img: 'assets/images/Copa-de-Cristal-Soplado.jpg', polaroids: ['🔥 Fundido', '💨 Soplado', '❄️ Enfriado'], story: 'Inmaculada sopla cristal en la Real Fábrica de La Granja. Cada copa lleva técnicas del siglo XVIII.', details: ['Cristal soplado', 'Hecho a mano', '350ml'] },
    { id: 24, cat: 'vidrio', title: 'Lámpara de Vidrio Reciclado', artisan: 'Tomás Iglesias', initials: 'TI', live: false, region: 'Barcelona, Cataluña', price: 135, badge: 'Eco', quote: '«Cada botella que reciclo es una estrella menos en el vertedero.»', img: 'assets/images/Lámpara-de-Vidrio-Reciclado.jpg', polaroids: ['♻️ Recogida', '🔥 Fusión', '💡 Montaje'], story: 'Tomás funde botellas de vino recicladas para crear lámparas únicas. El color depende del vidrio original.', details: ['Vidrio reciclado', 'LED incluido', 'Alt. 30cm'] },
    { id: 25, cat: 'vidrio', title: 'Vidriera Modernista en Miniatura', artisan: 'Gloria Puig', initials: 'GP', live: true, region: 'Barcelona, Cataluña', price: 210, badge: 'Arte', quote: '«Reproduzco Gaudí a escala para que entre en cualquier hogar.»', img: 'assets/images/Vidriera Modernista en Miniatura.jpg', polaroids: ['✏️ Diseño', '✂️ Cortado', '🪟 Emplomado'], story: 'Gloria reproduce vidrieras del Modernismo catalán en miniatura. Usa la técnica de emplomado tradicional.', details: ['Vidrio emplomado', 'Pared', '25x35cm'] },
    { id: 26, cat: 'vidrio', title: 'Set de Vasos Gordiola', artisan: 'Miquel Gordiola', initials: 'MG', live: false, region: 'Algaida, Mallorca', price: 85, badge: 'Set de 4', quote: '«Cada burbuja en el vidrio es una firma de autenticidad.»', img: 'assets/images/Set-de-Vasos-Gordiola.jpg', polaroids: ['🔥 Horno', '💨 Soplado', '🥂 Acabado'], story: 'La familia Gordiola sopla vidrio en Mallorca desde 1719. Las burbujas naturales son marca de autenticadad.', details: ['Vidrio soplado', 'Set 4 uds.', '300ml c/u'] },

    // ── METAL (4) ──
    { id: 27, cat: 'metal', title: 'Cuchillo Navaja Artesanal', artisan: 'Joaquín Blanco', initials: 'JB', live: true, region: 'Albacete', price: 125, badge: 'Forja', quote: '«El acero tiene memoria. Mi trabajo es darle forma a sus recuerdos.»', img: 'assets/images/product-metalknife.png', polaroids: ['🔥 Forja', '⚒️ Templado', '✂️ Afilado'], story: 'Joaquín forja navajas albaceteñas con acero al carbono. El mango de asta de toro es un arte en sí mismo.', details: ['Acero carbono', 'Mango de asta', 'Hoja 10cm'] },
    { id: 28, cat: 'metal', title: 'Candelabro de Hierro Forjado', artisan: 'Elena Morales', initials: 'EM', live: false, region: 'Toledo', price: 95, badge: 'Forja', quote: '«Cada golpe del martillo en la fragua es como el latido de un corazón de fuego.»', img: 'assets/images/Candelabro-de-Hierro-Forjado.jpg', polaroids: ['🔥 Fragua', '⚒️ Forjado', '🌀 Curvado'], story: 'Elena trabaja el hierro forjado toledano. Sus candelabros evocan la estética de las iglesias medievales.', details: ['Hierro forjado', '3 velas', 'Alt. 25cm'] },
    { id: 29, cat: 'metal', title: 'Pendientes de Plata Filigrana', artisan: 'Sofía Delgado', initials: 'SD', live: true, region: 'Salamanca', price: 58, badge: 'Joyería', quote: '«La filigrana es escribir poesía con hilos de plata.»', img: 'assets/images/Pendientes de Plata Filigrana.jpg', polaroids: ['💎 Plata', '🔧 Filigrana', '✨ Pulido'], story: 'Sofía domina la filigrana salmantina, donde hilos de plata de 0.3mm crean encajes metálicos.', details: ['Plata 925', 'Filigrana', 'Largo 4cm'] },
    { id: 30, cat: 'metal', title: 'Campana de Bronce Artesanal', artisan: 'Alberto Vega', initials: 'AV', live: false, region: 'Meruelo, Cantabria', price: 175, badge: 'Fundición', quote: '«Cada campana tiene su propia voz. Mi trabajo es afinársela.»', img: 'assets/images/Campana de Bronce Artesanal.jpg', polaroids: ['🔥 Fundición', '🔨 Moldeo', '🔔 Afinado'], story: 'Alberto funde campanas de bronce en Cantabria. Cada pieza se afina por percusión hasta encontrar su nota.', details: ['Bronce', 'Fundición', 'Ø 12cm', 'Sonora'] }
];

window.appProducts = products;
